apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mairror_api.fullname" . }}
  labels:
    {{- include "mairror_api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.mairror_api.autoscaling.enabled }}
  replicas: {{ .Values.mairror_api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mairror_api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.mairror_api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mairror_api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.mairror_api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mairror_api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.mairror_api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.mairror_api.container.name }}
          securityContext:
            {{- toYaml .Values.mairror_api.securityContext | nindent 12 }}
          image: "{{ .Values.mairror_api.image.repository }}:{{ .Values.mairror_api.image.tag }}"
          imagePullPolicy: {{ .Values.mairror_api.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 8000
              protocol: TCP
          {{- if .Values.mairror_api.secrets.create }}
          envFrom:
          - secretRef:
              name: {{ .Values.mairror_api.secrets.name }}
          {{- end }}
          resources:
            {{- toYaml .Values.mairror_api.resources | nindent 12 }}
            {{- with .Values.mairror_api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mairror_api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mairror_api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
