{{- if .Values.mairror_bot.secrets.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.mairror_bot.secrets.name }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
data:
  {{- range $key, $value := .Values.mairror_bot.secrets.values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
