{{- if .Values.mairror_front.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mairror_front.serviceAccountName" . }}
  labels:
    {{- include "mairror_front.labels" . | nindent 4 }}
  {{- with .Values.mairror_front.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
