apiVersion: v1
kind: Service
metadata:
  name: {{ include "mairror_front.fullname" . }}
  labels:
    {{- include "mairror_front.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mairror_front.service.type }}
  ports:
    - port: {{ .Values.mairror_front.service.port }}
      targetPort: front
      protocol: TCP
      name: http
  selector:
    {{- include "mairror_front.selectorLabels" . | nindent 4 }}
