{{- if .Values.mairror_predictor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mairror_predictor.serviceAccountName" . }}
  labels:
    {{- include "mairror_predictor.labels" . | nindent 4 }}
  {{- with .Values.mairror_predictor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
