{{- if .Values.mairror_bot.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mairror_bot.serviceAccountName" . }}
  labels:
    {{- include "mairror_bot.labels" . | nindent 4 }}
  {{- with .Values.mairror_bot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
